global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: ui-quality-otel
    static_configs:
      - targets: ["otel-collector:9464"]
